/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addressbook;

import classBD.conectionBD;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
        
    private int numberRows ;
    private conectionBD connectionBD = null;
    
    public NewJInternalFrame() {
        initComponents();
        connectionBD = new conectionBD();
        idJtextField.setText(""+(connectionBD.selectLastContact()+1));
    }
    
    private void checkDataBase(){
        idJtextField.setText(""+connectionBD.checkDataBase());
    }
    
    
    
    private void insertNewRow(){        
        connectionBD.insertNewContact(Integer.parseInt(idJtextField.getText()), 
                                        nameJtextField.getText(), 
                                        surnameJtextFIeld.getText(), 
                                        addressJtextField.getText(), 
                                        countryJtextField.getText());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idJtextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameJtextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        surnameJtextFIeld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressJtextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        countryJtextField = new javax.swing.JTextField();
        agreeJbutton = new javax.swing.JButton();
        cancelJbutton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Add new contact");

        jPanel1.setBackground(new java.awt.Color(208, 207, 205));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("ID: ");
        jLabel1.setOpaque(true);

        idJtextField.setEditable(false);
        idJtextField.setEnabled(false);

        jLabel2.setText("Name: ");
        jLabel2.setOpaque(true);

        nameJtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJtextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Surname: ");
        jLabel3.setOpaque(true);

        jLabel4.setText("Address: ");
        jLabel4.setOpaque(true);

        jLabel5.setText("Country: ");
        jLabel5.setOpaque(true);

        agreeJbutton.setText("AGREE");
        agreeJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeJbuttonActionPerformed(evt);
            }
        });

        cancelJbutton.setText("CANCEL");
        cancelJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(agreeJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(cancelJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(countryJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(surnameJtextFIeld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addressJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameJtextField)
                                .addComponent(idJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(surnameJtextFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(countryJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agreeJbutton)
                    .addComponent(cancelJbutton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameJtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJtextFieldActionPerformed
        checkFields();
    }//GEN-LAST:event_nameJtextFieldActionPerformed

    private void agreeJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeJbuttonActionPerformed
        checkFields();
        insertNewRow();        
    }//GEN-LAST:event_agreeJbuttonActionPerformed

    private void cancelJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJbuttonActionPerformed
        clearJtextFields();
    }//GEN-LAST:event_cancelJbuttonActionPerformed

    private void clearJtextFields(){
        nameJtextField.setText("");
        surnameJtextFIeld.setText("");
        addressJtextField.setText("");
        countryJtextField.setText("");
    }
    
    
    private void checkFields(){
        if(nameJtextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please insert a name of the new contact");
            nameJtextField.requestFocus();
        }else{
            if(surnameJtextFIeld.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please insert a surname of the new contact");
                surnameJtextFIeld.requestFocus();
            }else{
                if(addressJtextField.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Please insert a address of the new contact");
                    addressJtextField.requestFocus();
                }else{
                    if(countryJtextField.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Please insert a country of the new contact");
                        countryJtextField.requestFocus();
                    }
                }
            }
        }
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJtextField;
    private javax.swing.JButton agreeJbutton;
    private javax.swing.JButton cancelJbutton;
    private javax.swing.JTextField countryJtextField;
    private javax.swing.JTextField idJtextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameJtextField;
    private javax.swing.JTextField surnameJtextFIeld;
    // End of variables declaration//GEN-END:variables
}
